[package]
name = "musical-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.13.2", features = ["dynamic_linking"]}
bevy_egui = "0.27.0"

[profile.dev.package."*"]
opt-level = 3
